import type { Metadata } from 'next';
import ClientProviders from './ClientProviders';
import './globals.css';

export const metadata: Metadata = {
  title: 'Strapi Next.js',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
